//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jingZe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialLoss
    {
        public int ID { get; set; }
        public Nullable<int> RFIDID { get; set; }
        public string Line { get; set; }
        public string Status { get; set; }
        public Nullable<double> GFweight { get; set; }
        public Nullable<double> Resinweight { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string OrderNo { get; set; }
        public string Reserver1 { get; set; }
        public string Reserver2 { get; set; }
        public string Reserver3 { get; set; }
        public Nullable<int> CS { get; set; }
    }
}
