//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jingZe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProWeigth
    {
        public int ID { get; set; }
        public Nullable<int> RFIDID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> FinishNum { get; set; }
        public Nullable<int> OrderProNo { get; set; }
        public Nullable<int> ProNo { get; set; }
        public string ProName { get; set; }
        public string spec { get; set; }
        public string Custoner { get; set; }
        public string MPWeigth { get; set; }
        public string PGWeigth { get; set; }
        public string MGWeigth { get; set; }
        public string JGWeigth { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
