//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JingZeServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JZZSEntities1 : DbContext
    {
        public JZZSEntities1()
            : base("name=JZZSEntities1")
        {
        }
        public JZZSEntities1(string connection)
        : base("name=JZZSEntities1")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RERFID> RERFID { get; set; }
        public virtual DbSet<MaterialLoss> MaterialLoss { get; set; }
        public virtual DbSet<ProWeigth> ProWeigth { get; set; }
        public virtual DbSet<GZID> GZID { get; set; }
        public virtual DbSet<material> material { get; set; }
    }
}
