//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JingZeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public string specification { get; set; }
        public Nullable<double> resinWeight { get; set; }
        public Nullable<double> fgWeight { get; set; }
        public Nullable<double> qbq { get; set; }
        public Nullable<double> qbh { get; set; }
        public Nullable<double> gcRange { get; set; }
        public Nullable<double> gfWeight { get; set; }
    }
}
